[package]
name = "dioxus-shareables"
author = "Tamvana Makuluni <29412577+emakman@users.noreply.github.com>"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Hooks for sharing structures between components0."
documentation = "https://docs.rs/dioxus-shareables"
repository = "https://github.com/emakman/dioxus-shareables"
readme = "README.md"
keywords = ["dioxus"]
exclude = ["deny.toml"]

[features]
debugging = []

[dependencies]
dioxus-core = "0.2.1"
paste = "1.0.8"

[dev-dependencies]
dioxus = "0.2.4"
