[package]
name = "dioxus-shareables"
author = "Tamvana Makuluni <29412577+emakman@users.noreply.github.com>"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "Hooks for sharing structures between components."
documentation = "https://docs.rs/dioxus-shareables"
repository = "https://github.com/emakman/dioxus-shareables"
readme = "README.md"
keywords = ["dioxus"]
include = ["src/**/*.rs", "Cargo.toml", "LICENSE"]

[features]
debugging = []

[dependencies]
dioxus-core = "0.2.1"
paste = "1"

[dev-dependencies]
dioxus = "0.2.4"
