[package]
name = "dioxus-shareables"
authors = ["Tamvana Makuluni"]
version = "0.2.4"
edition = "2021"
license = "MIT"
description = "Hooks for sharing structures between components."
documentation = "https://docs.rs/dioxus-shareables"
repository = "https://github.com/emakman/dioxus-shareables"
readme = "README.md"
keywords = ["dioxus"]
include = ["src/**/*.rs", "Cargo.toml", "LICENSE"]

[features]
default = [ "dioxus-core-0-2-1" ]
debug = []
dioxus-git = [ "dioxus-core-git" ]

[dependencies]
dioxus-core-0-2-1 = { package = "dioxus-core", version = "0.2.1", optional = true }
dioxus-core-git = { package = "dioxus-core", git = "https://github.com/dioxuslabs/dioxus", optional = true }
paste = "1"

[dev-dependencies]
dioxus-0-2-4 = { package = "dioxus", version = "0.2.4" }
dioxus-git = { package = "dioxus", git = "https://github.com/dioxuslabs/dioxus" }
